resources:
  - name: pythonturtle_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: ric03uec/PythonTurtle
      branch: master

 ## Job description:
jobs:
  - name: windows_build
    type: runSh
    runtime:
      nodePool: dyn_win16
      container: false
    steps:
      - IN: pythonturtle_repo
      - TASK:
          name: build app on windows node
          runtime:
            options:
              env:
                - PYTHON_PATH: 'C:\Users\Administrator\AppData\Local\Programs\Python\Python37'
          script:
            - Get-Process
            - pushd $(shipctl get_resource_state "pythonturtle_repo")
            - ls
            - Get-ChildItem Env:Path | format-list
            - choco install -y python --version 3.6.3
            #- $env:Path="$env:Path;C:\Users\Administrator\AppData\Local\Programs\Python\Python37;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\Scripts"
            - Get-ChildItem Env:Path | format-list
            - python --version
            - 'C:\Users\Administrator\AppData\Local\Programs\Python\Python37\python.exe -m pip install PyInstaller wxPython'
              #- python.exe setup.py clean bundle
