resources:
  - name: pythonturtle_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: ric03uec/PythonTurtle
      branch: master

 ## Job description:
jobs:
  - name: windows_build
    type: runSh
    allowPublicAccess: true
    runtime:
      nodePool: dyn_win16
    steps:
      - IN: pythonturtle_repo
      - TASK:
          name: build app on windows node
          script:
            - Get-Process
            - pushd $(shipctl get_resource_state "pythonturtle_repo")
              #- choco install -y python --version 3.6.3
            - Get-ChildItem Env:Path | format-list
            - python --version
            - python -m pip install PyInstaller wxPython
            - python setup.py clean bundle
