resources:
  - name: pythonturtle_repo
    type: gitRepo
    integration: gh_ric03uec
    pointer:
      sourceName: ric03uec/PythonTurtle
      branch: master

 ## Job description:
jobs:
  - name: windows_build
    type: runSh
    runtime:
      nodePool: cus_win16
    steps:
      - IN: pythonturtle_repo
      - TASK:
          name: build app on windows node
          script:
            - Get-Process
            - docker images
            - docker ps
