resources:
  - name: pythonturtle_repo
    type: gitRepo
    integration: ric03uec-github
    buildOnPullRequest: true
    pointer:
      sourceName: ric03uec/PythonTurtle
      branch: master

 ## Job description:
jobs:
  - name: windows_build
    type: runSh
    allowPublicAccess: true
    runtime:
      nodePool: dyn_win16
    steps:
      - IN: pythonturtle_repo
      - TASK:
          name: build PythonTurtle on windows node
          script:
            - systeminfo
            - Get-Process
            - pushd $(shipctl get_resource_state "pythonturtle_repo")
            - python --version
            - choco install python --version 3.6.3
            - python3 --version
            - python -m pip install PyInstaller wxPython
            - python setup.py clean bundle
