resources:
  - name: pythonturtle_repo
    type: gitRepo
    integration: ric03uec-github
    buildOnPullRequest: true
    pointer:
      sourceName: ric03uec/PythonTurtle
      branch: master

 ## Job description:
jobs:
  - name: windows_build
    type: runSh
    allowPublicAccess: true
    runtime:
      nodePool: dyn_win16
    steps:
      - IN: pythonturtle_repo
      - TASK:
          name: build PythonTurtle on windows node
          script:
            - systeminfo
            - Get-Process
            - python --version
            - pushd $(shipctl get_resource_state "pythonturtle_repo")
            - choco install -y python --version 3.6.3
            - 'C:\Python36\python.exe --version'
            - 'C:\Python36\python.exe -m pip install PyInstaller wxPython'
            - 'C:\Python36\python.exe  setup.py clean bundle'

  - name: push_artifacts
    type: runSh
    allowPublicAccess: true
    runtime:
      nodePool: dyn_win16
    steps:
      - IN: windows_build
      - TASK:
          name: push artifacts somewhere
          script:
            - systeminfo
