resources:
  - name: pythonturtle_repo
    type: gitRepo
    integration: ric03uec-github
    pointer:
      sourceName: ric03uec/PythonTurtle
      branch: master

 ## Job description:
jobs:
  - name: windows_build
    type: runSh
    runtime:
      nodePool: dyn_win16
      container: false
    steps:
      - IN: pythonturtle_repo
      - TASK:
          name: build app on windows node
          runtime:
            options:
              env:
                - PYTHON_PATH: 'C:\Users\Administrator\AppData\Local\Programs\Python\Python37'
          script:
            - Get-Process
            - pushd $(shipctl get_resource_state "pythonturtle_repo")
            - wget -OutFile python.exe -Uri "https://www.python.org/ftp/python/3.7.0/python-3.7.0-amd64.exe"
            - $env:PYTHON_PATH\python.exe -m pip install PyInstaller wxPython
            - $env:PYTHON_PATH\python.exe setup.py clean bundle
